Final-Merge/Pubsite-VentesB2B/Models/News.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;
using System.Runtime.Serialization;

namespace Pubsite_VentesB2B.Models
{
    public enum NewsType { Featured, Trending }
    public partial class News
    {
        public int NewsID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? NewsDate { get; set; }

        public int? ContentID { get; set; }

        public virtual ContentDetail ContentDetail { get; set; }

        public string NewsType
        {
            get
            {
                return this.N_Type.ToString();
            }
            set
            {
                N_Type = value.ParseEnum<NewsType>();
            }
        }

        [NotMapped]
        public NewsType N_Type { get; set; }
    }

    public static class StringExtensions
    {
        public static T ParseEnum<T>(this string value)
        {
            return (T)Enum.Parse(typeof(T), value, true);
        }
    }
}

Final-Merge/Pubsite-VentesB2B/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Pubsite_VentesB2B.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Web.Security;
using PagedList;
using PagedList.Mvc;

namespace Pubsite_VentesB2B.Controllers
{
    [Authorize]
    public class NewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index(int? page, string searchText = "", string Type="")
        {
            IPagedList<News> news;
            searchText = searchText.Trim();
            Type = Type.Trim();
            if (!string.IsNullOrEmpty(Type))
            {
              news = db.News.Include(n => n.ContentDetail).ToList().Where(n => (n.ContentDetail.Title.Contains(searchText.ToString())) && (n.NewsType.Contains(Type))).OrderByDescending(n=>n.NewsID).ToList().ToPagedList(page ?? 1, 10);
            }
            else
            {
              news = db.News.Include(n => n.ContentDetail).ToList().Where(n => n.ContentDetail.Title.Contains(searchText.ToString())).OrderByDescending(n=>n.NewsID).ToList().ToPagedList(page ?? 1, 10);
            }
            return View(news);
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = await db.News.FindAsync(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        public ActionResult Create()
        {
            ViewBag.ContentID = new SelectList(db.ContentDetails, "ContentID", "Title");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(News news)
        {
            if (ModelState.IsValid)
            {
                if (news.ContentDetail.Upload.ContentLength > 0)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(news.ContentDetail.Upload.FileName);
                    string path = Path.Combine(Server.MapPath("~/Uploads/News/Images"), fileName);
                    news.ContentDetail.Upload.SaveAs(path);
                    news.ContentDetail.Image = "Uploads/News/Images/" + fileName;
                }
                ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
                news.ContentDetail.CreatedDate = DateTime.Now;
                news.ContentDetail.UpdatedDate = DateTime.Now;

                news.ContentDetail.CreatedById = user.Id;
                news.ContentDetail.UpdatedById = user.Id;
                db.News.Add(news);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ContentID = new SelectList(db.ContentDetails, "ContentID", "Title", news.ContentID);
            return View(news);
        }

        // GET: News/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = await db.News.FindAsync(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContentID = news.ContentID;
            return View(news);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(News news)
        {
            if (ModelState.IsValid)
            {
                if (news.ContentDetail.Upload!=null && news.ContentDetail.Upload.ContentLength > 0)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(news.ContentDetail.Upload.FileName);
                    string path = Path.Combine(Server.MapPath("~/Uploads/News/Images"), fileName);
                    news.ContentDetail.Upload.SaveAs(path);
                    news.ContentDetail.Image = "Uploads/News/Images/" + fileName;
                }
                ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
                news.ContentDetail.UpdatedDate = DateTime.Now;
                news.ContentDetail.UpdatedById = user.Id;
                db.Entry(news).State = EntityState.Modified;
                db.Entry(news.ContentDetail).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Details/" + news.NewsID);
            }
            return View(news);
        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = await db.News.FindAsync(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthFilter(Roles = "AppAdmin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            News news = await db.News.FindAsync(id);
            db.News.Remove(news);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Final-Merge/Pubsite-VentesB2B/Views/News/Create.cshtml
@model Pubsite_VentesB2B.Models.News
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}
<h2>Create</h2>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
@using (Html.BeginForm("Create", "News", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>News</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NewsType, "News Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(x => x.N_Type, "Select News Type", new { @class = "form-control", @Required = "required" })
                @Html.ValidationMessageFor(model => model.NewsType, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ContentDetail.Title, "Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentDetail.Title, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
                @Html.ValidationMessageFor(model => model.ContentDetail.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ContentDetail.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ContentDetail.Description, new { @class = "form-control col-md-12", @rows = 5, @Required = "required" })
                @Html.ValidationMessageFor(model => model.ContentDetail.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContentDetail.URL, "URL Link", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentDetail.URL, new { htmlAttributes = new { @class = "form-control", @pattern = "https?://.+", @Required = "required" } })
                @Html.ValidationMessageFor(model => model.ContentDetail.URL, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ContentDetail.Author, "Author", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentDetail.Author, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
                @Html.ValidationMessageFor(model => model.ContentDetail.Author, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ContentDetail.Keywords, "Keywords", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentDetail.Keywords, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
                @Html.ValidationMessageFor(model => model.ContentDetail.Keywords, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ContentDetail.Upload, "Banner Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ContentDetail.Upload, new { type = "file", @onclick = "readURL(this)", @Required = "required" })
                <label id="lblFileSize"></label>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ContentDetail.CompanyName, "Company Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentDetail.CompanyName, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
                @Html.ValidationMessageFor(model => model.ContentDetail.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NewsDate, "News Date", htmlAttributes: new { @class = "control-label col-md-2", @Required = "required" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewsDate, new { htmlAttributes = new { @class = "form-control date-inputmask" } })
                @Html.ValidationMessageFor(model => model.NewsDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.ContentDetail.HideOnSite)
                @Html.LabelFor(model => model.ContentDetail.HideOnSite, "Hide On Site", htmlAttributes: new { @class = "control-label col-md-2" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script type="text/javascript">
    document.getElementById('NewsDate').max = new Date(new Date().getTime() - new Date().getTimezoneOffset() * 60000).toISOString().split("T")[0];
</script>
<script src="~/Scripts/App/App.js"></script>

Final-Merge/Pubsite-VentesB2B/Views/News/Delete.cshtml
@model Pubsite_VentesB2B.Models.News

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>News</h4>
    <table class="table col-md-12">
        <tr>
            <td>@Html.DisplayNameFor(model => model.NewsType)</td>
            <td>@Html.DisplayFor(model => model.NewsType)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.Title)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.Title)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.Description)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.Description)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.URL)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.URL, new { @target = "_blank" })</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.Author)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.Author)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.Keywords)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.Keywords)</td>
        </tr>
        <tr>
            <td>Banner Image</td>
            @*<td><img src="~/@Url.Content(Model.ContentDetail.Image)" alt="Image" /></td>*@
            <td><img src="~/@Html.DisplayFor(model=>model.ContentDetail.Image)" class="col-md-8" alt="Image" /></td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.CompanyName)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.CompanyName)</td>
        <tr>
            <td>@Html.DisplayNameFor(model => model.NewsDate)</td>
            <td>@Html.DisplayFor(model => model.NewsDate)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.HideOnSite)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.HideOnSite)</td>
        </tr>
    </table>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Final-Merge/Pubsite-VentesB2B/Views/News/Details.cshtml
@model Pubsite_VentesB2B.Models.News

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>News</h4>
    <table class="table col-md-12">
        <tr>
            <td>@Html.DisplayNameFor(model => model.NewsType)</td>
            <td>@Html.DisplayFor(model => model.NewsType)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.Title)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.Title)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.Description)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.Description)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.URL)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.URL, new { @target = "_blank" })</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.Author)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.Author)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.Keywords)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.Keywords)</td>
        </tr>
        <tr>
            <td>Banner Image</td>
            @*<td><img src="~/@Url.Content(Model.ContentDetail.Image)" alt="Image" /></td>*@
            <td><img src="~/@Html.DisplayFor(model=>model.ContentDetail.Image)" class="col-md-8" alt="Image" /></td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.CompanyName)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.CompanyName)</td>
        <tr>
            <td>@Html.DisplayNameFor(model => model.NewsDate)</td>
            <td>@Html.DisplayFor(model => model.NewsDate)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.ContentDetail.HideOnSite)</td>
            <td>@Html.DisplayFor(model => model.ContentDetail.HideOnSite)</td>
        </tr>
    </table>
</div>
<br /><br />
<p>

    @Html.ActionLink("Back to List", "Index") | 
    @Html.ActionLink("Edit", "Edit", new { id = Model.NewsID }) | 
    @Html.ActionLink("Delete", "Delete", new { id = Model.NewsID })
</p>

Final-Merge/Pubsite-VentesB2B/Views/News/Edit.cshtml
@model Pubsite_VentesB2B.Models.News

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}

<h2>Edit</h2>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
@using (Html.BeginForm("Edit", "News", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>News</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.NewsID)
    @Html.HiddenFor(model => model.ContentID)
    @Html.HiddenFor(model => model.ContentDetail.ContentID)
    @Html.HiddenFor(model => model.ContentDetail.Image)
    <div class="form-group">
        @Html.LabelFor(model => model.NewsType, "News Type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(x => x.N_Type, "Select News Type", new { @class = "form-control", @Required = "required" })
            @Html.ValidationMessageFor(model => model.NewsType, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ContentDetail.Title, "Title", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContentDetail.Title, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.ContentDetail.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContentDetail.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.ContentDetail.Description, new { @class = "form-control col-md-12", @rows = 5, @Required = "required" })
            @Html.ValidationMessageFor(model => model.ContentDetail.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContentDetail.URL, "URL Link", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContentDetail.URL, new { htmlAttributes = new { @class = "form-control", @pattern = "https?://.+", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.ContentDetail.URL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContentDetail.Author, "Author", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContentDetail.Author, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.ContentDetail.Author, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContentDetail.Keywords, "Keywords", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContentDetail.Keywords, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.ContentDetail.Keywords, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ContentDetail.Upload, "Banner Image", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.ContentDetail.Upload, new { type = "file" })
            <label id="lblFileSize"></label>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ContentDetail.Image, "Current Banner Image", htmlAttributes: new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            <td><img src="~/@Html.DisplayFor(model=>model.ContentDetail.Image)" alt="Image" class="col-md-8" /></td>
        </div>
    </div>
     <div class="form-group">
            @Html.LabelFor(model => model.ContentDetail.CompanyName, "Company Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentDetail.CompanyName, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
                @Html.ValidationMessageFor(model => model.ContentDetail.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NewsDate, "News Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NewsDate, new { htmlAttributes = new { @class = "form-control date-inputmask", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.NewsDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.ContentDetail.HideOnSite)
            @Html.LabelFor(model => model.ContentDetail.HideOnSite, "Hide On Site", htmlAttributes: new { @class = "control-label col-md-2" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Update" class="btn btn-default" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Back", "Details", new { id = Model.NewsID })
</div>
<script src="~/Scripts/App/App.js"></script>

Final-Merge/Pubsite-VentesB2B/Views/News/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<Pubsite_VentesB2B.Models.News>

@{
  ViewBag.Title = "Search News";
  Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}

<h2>Search News</h2>
@using (Html.BeginForm("Index", "NewsList", FormMethod.Get))
{
  <div class="form-group">
    <div class="row">
      <div class="col-md-2">
      </div>
      <div class="col-md-6">
        <div class="input-group mb-3">
          <input type="text" class="form-control" id="searchText" name="searchText" placeholder="Search" aria-label="News Title" aria-describedby="basic-addon2">
          <input type="hidden" class="form-control" id="Type" name="Type" value="@Request.QueryString["Type"]" />
          <div class="input-group-append">
            <input type="submit" id="btnSubmit" class="input-group-text" />
          </div>
        </div>
      </div>
      <div>
      </div>
    </div>
  </div>
}
<p>
  @Html.ActionLink("Add News", "Create")
</p>
<table class="table table-striped table-bordered">
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.First().ContentDetail.Title)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.First().ContentDetail.Description)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.First().NewsType)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.First().NewsDate)
    </th>
    <th>

    </th>
  </tr>

  @foreach (var item in Model)
  {
<tr>
  <td>
    @Html.DisplayFor(modelItem => item.ContentDetail.Title)
  </td>
  <td>
    @Html.DisplayFor(modelItem => item.ContentDetail.Description)
  </td>
  <td>
    @Html.DisplayFor(modelItem => item.NewsType)
  </td>
  <td>
    @Html.DisplayFor(modelItem => item.NewsDate)
  </td>
  <td>
    @Html.ActionLink("Details", "Details", new { id = item.NewsID })
  </td>
</tr>
  }

</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, Type = Request.QueryString["Type"], searchText = Request.QueryString["searchText"] }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true })