Final-Merge/Pubsite-VentesB2B/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;

namespace Pubsite_VentesB2B.Models
{
    public enum EventType
    {
      [Display(Name = "Conference")]
      Conference,

      [Display(Name = "OnDemand Webinar")]
      OnDemand,

      [Display(Name = "Live Webinar")]
      Live
    }

    [Table("Event")]
    public partial class Event
    {
        public int EventID { get; set; }

        public int? AddressID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? StartDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? EndDate { get; set; }

        public int? ContentID { get; set; }

        public virtual Address Address { get; set; }

        public virtual ContentDetail ContentDetail { get; set; }

        public string EventType
        {
            get
            {
                return this.E_Type.ToString();
            }
            set
            {
                E_Type = value.ParseEnum<EventType>();
            }
        }

        [NotMapped]
        public EventType E_Type { get; set; }
    }
}

Final-Merge/Pubsite-VentesB2B/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PagedList;
using PagedList.Mvc;
using Pubsite_VentesB2B.Models;

namespace Pubsite_VentesB2B.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Events
        public ActionResult Index(int? page, string searchText = "", string Type="")
        {
            IPagedList<Event> events;
            searchText = searchText.Trim();
            Type = Type.Trim();
            if (!string.IsNullOrEmpty(Type))
            {
              events = db.Events.Include(e => e.ContentDetail).ToList().Where(e => (e.ContentDetail.Title.Contains(searchText.ToString())) && (e.EventType.Contains(Type))).OrderByDescending(e=>e.EventID).ToList().ToPagedList(page ?? 1, 10);
            }
            else
            {
              events = db.Events.Include(e => e.ContentDetail).ToList().Where(e => e.ContentDetail.Title.Contains(searchText.ToString())).OrderByDescending(e=>e.EventID).ToList().ToPagedList(page ?? 1, 10);
            }
            return View(events);
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            return View(events);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Event events)
        {
            if (ModelState.IsValid)
            {
                events.ContentDetail.CreatedDate = DateTime.Now;
                events.ContentDetail.UpdatedDate = DateTime.Now;
                if (events.ContentDetail.Upload.ContentLength > 0)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(events.ContentDetail.Upload.FileName);
                    string path = Path.Combine(Server.MapPath("~/Uploads/Events/Images"), fileName);
                    events.ContentDetail.Upload.SaveAs(path);
                    events.ContentDetail.Image = "Uploads/Events/Images/" + fileName;
                }
                ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
                events.ContentDetail.CreatedDate = DateTime.Now;
                events.ContentDetail.UpdatedDate = DateTime.Now;
                events.ContentDetail.CreatedById = user.Id;
                events.ContentDetail.UpdatedById = user.Id;
                db.Events.Add(events);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(events);
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            return View(events);
        }

        // POST: Events/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Event events)
        {
            if (ModelState.IsValid)
            {
                if (events.ContentDetail.Upload != null && events.ContentDetail.Upload.ContentLength > 0)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(events.ContentDetail.Upload.FileName);
                    string path = Path.Combine(Server.MapPath("~/Uploads/News/Images"), fileName);
                    events.ContentDetail.Upload.SaveAs(path);
                    events.ContentDetail.Image = "Uploads/News/Images/" + fileName;
                }
                ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
                events.ContentDetail.UpdatedDate = DateTime.Now;
                events.ContentDetail.UpdatedById = user.Id;
                db.Entry(events).State = EntityState.Modified;
                db.Entry(events.ContentDetail).State = EntityState.Modified;
                db.Entry(events.Address).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(events);
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            return View(events);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthFilter(Roles = "AppAdmin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Event events = db.Events.Find(id);
            db.Events.Remove(events);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Final-Merge/Pubsite-VentesB2B/Views/Events/Create.cshtml
@model Pubsite_VentesB2B.Models.Event
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}
<h2>Create</h2>
<script src="~/Scripts/jquery-3.3.1.js"></script>
@using (Html.BeginForm("Create", "Events", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <h4>Event</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" id="divEventType">
        @Html.LabelFor(model => model.EventType, "Event Type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(x => x.E_Type, "Select Event Type", new { @class = "form-control", @Required = "required" })
            @Html.ValidationMessageFor(model => model.EventType, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divContentDetailTitle">
        @Html.LabelFor(model => model.ContentDetail.Title, "Title", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContentDetail.Title, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.ContentDetail.Title, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divContentDetailDescription">
        @Html.LabelFor(model => model.ContentDetail.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.ContentDetail.Description, new { @class = "form-control col-md-12", @rows = 5, @Required = "required" })
            @Html.ValidationMessageFor(model => model.ContentDetail.Description, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divContentDetailURL">
        @Html.LabelFor(model => model.ContentDetail.URL, "URL Link", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContentDetail.URL, new { htmlAttributes = new { @class = "form-control", @Required = "required", @pattern = "https?://.+" } })
            @Html.ValidationMessageFor(model => model.ContentDetail.URL, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divContentDetailKeywords">
        @Html.LabelFor(model => model.ContentDetail.Keywords, "Keywords", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContentDetail.Keywords, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.ContentDetail.Keywords, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divContentDetailKeywords">
        @Html.LabelFor(model => model.ContentDetail.CompanyName, "Company Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContentDetail.CompanyName, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.ContentDetail.CompanyName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divContentDetailUpload">
        @Html.LabelFor(model => model.ContentDetail.Upload, "Banner Image", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.ContentDetail.Upload, new { type = "file", @Required = "required" })
            <label id="lblFileSize"></label>
        </div>
    </div>
    <div class="form-group" id="divAddressCity">
        @Html.LabelFor(model => model.Address.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address.City, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.Address.City, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divAddressState">
        @Html.LabelFor(model => model.Address.State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address.State, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.Address.State, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divAddressCountry">
        @Html.LabelFor(model => model.Address.Country, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address.Country, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.Address.Country, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divStartDate">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divEndDate">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10" id="divContentDetailHideOnSite">
            @Html.CheckBoxFor(model => model.ContentDetail.HideOnSite)
            @Html.LabelFor(model => model.ContentDetail.HideOnSite, "Hide On Site", htmlAttributes: new { @class = "control-label col-md-2" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script type="text/javascript">
    document.getElementById('StartDate').min = new Date(new Date().getTime() - new Date().getTimezoneOffset() * 60000).toISOString().split("T")[0];
    $(document).ready(function () {
        EventTypeCheck();
    });
    $('#StartDate').change(function () {
        document.getElementById('EndDate').value = "";
        document.getElementById('EndDate').min = document.getElementById('StartDate').value;
    });

    $('#E_Type').change(function () {
        EventTypeCheck();
    });

    function EventTypeCheck() {
      if ($('#E_Type').find(":selected").text() == "OnDemand Webinar") {
        $('#divStartDate').hide();
        $("#StartDate").removeAttr("required");
        $('#divEndDate').hide();
        $("#EndDate").removeAttr("required");
      }
      else {
        $('#divStartDate').show();
        $("#StartDate").attr("required", "required");
        $('#divEndDate').show();
        $("#EndDate").attr("required", "required");
      }
      if ($('#E_Type').find(":selected").text() == "Conference") {
        $('#divAddressCity').show();
        $("#Address_City").attr("required", "required");
        $('#divAddressState').show();
        $("#Address_State").attr("required", "required");
        $('#divAddressCountry').show();
        $("#Address_Country").attr("required", "required");
      }
      else {
        $('#divAddressCity').hide();
        $("#Address_City").removeAttr("required");
        $('#divAddressState').hide();
        $("#Address_State").removeAttr("required");
        $('#divAddressCountry').hide();
        $("#Address_Country").removeAttr("required");
      }
    }
</script>
<script src="~/Scripts/App/App.js"></script>

Final-Merge/Pubsite-VentesB2B/Views/Events/Edit.cshtml
@model Pubsite_VentesB2B.Models.Event

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}

<h2>Edit</h2>
<script src="~/Scripts/jquery-3.3.1.js"></script>

@using (Html.BeginForm("Edit", "Events", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Event</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.EventID)
    @Html.HiddenFor(model => model.ContentID)
    @Html.HiddenFor(model => model.Address.AddressID)
    @Html.HiddenFor(model => model.AddressID)
    @Html.HiddenFor(model => model.ContentDetail.ContentID)
    @Html.HiddenFor(model => model.ContentDetail.Image)
    <div class="form-group" id="divEventType">
        @Html.LabelFor(model => model.EventType, "Event Type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(x => x.E_Type, "Select Event Type", new { @class = "form-control", @Required = "required" })
            @Html.ValidationMessageFor(model => model.EventType, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divContentDetailTitle">
        @Html.LabelFor(model => model.ContentDetail.Title, "Title", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContentDetail.Title, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.ContentDetail.Title, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divContentDetailDescription">
        @Html.LabelFor(model => model.ContentDetail.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.ContentDetail.Description, new { @class = "form-control col-md-12", @rows = 5, @Required = "required" })
            @Html.ValidationMessageFor(model => model.ContentDetail.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" id="divContentDetailURL">
        @Html.LabelFor(model => model.ContentDetail.URL, "URL Link", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContentDetail.URL, new { htmlAttributes = new { @class = "form-control", @Required = "required", @pattern = "https?://.+" } })
            @Html.ValidationMessageFor(model => model.ContentDetail.URL, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divContentDetailKeywords">
        @Html.LabelFor(model => model.ContentDetail.Keywords, "Keywords", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContentDetail.Keywords, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.ContentDetail.Keywords, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divContentDetailKeywords">
        @Html.LabelFor(model => model.ContentDetail.CompanyName, "Company Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContentDetail.CompanyName, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.ContentDetail.CompanyName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divContentDetailUpload">
        @Html.LabelFor(model => model.ContentDetail.Upload, "Banner Image", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.ContentDetail.Upload, new { type = "file" })
            <label id="lblFileSize"></label>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ContentDetail.Image, "Current Banner Image", htmlAttributes: new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            <img src="~/@Html.DisplayFor(model=>model.ContentDetail.Image)" alt="Image" class="col-md-8" />
        </div>
    </div>
    <div class="form-group" id="divAddressCity">
        @Html.LabelFor(model => model.Address.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address.City, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.Address.City, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divAddressState">
        @Html.LabelFor(model => model.Address.State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address.State, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.Address.State, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divAddressCountry">
        @Html.LabelFor(model => model.Address.Country, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address.Country, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.Address.Country, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divStartDate">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" id="divEndDate">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", @Required = "required" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10" id="divContentDetailHideOnSite">
            @Html.CheckBoxFor(model => model.ContentDetail.HideOnSite)
            @Html.LabelFor(model => model.ContentDetail.HideOnSite, "Hide On Site", htmlAttributes: new { @class = "control-label col-md-2" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Update" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    document.getElementById('StartDate').min = new Date(new Date().getTime() - new Date().getTimezoneOffset() * 60000).toISOString().split("T")[0];
    $(document).ready(function () {
        EventTypeCheck();
    });
    $('#StartDate').change(function () {
        document.getElementById('EndDate').value = "";
        document.getElementById('EndDate').min = document.getElementById('StartDate').value;
    });

    $('#E_Type').change(function () {
        EventTypeCheck();
    });

    function EventTypeCheck() {
      if ($('#E_Type').find(":selected").text() == "OnDemand") {
        $('#divStartDate').hide();
        $("#StartDate").removeAttr("required");
        $('#divEndDate').hide();
        $("#EndDate").removeAttr("required");
      }
      else {
        $('#divStartDate').show();
        $("#StartDate").attr("required", "required");
        $('#divEndDate').show();
        $("#EndDate").attr("required", "required");
      }
      if ($('#E_Type').find(":selected").text() == "Conference") {
        $('#divAddressCity').show();
        $("#Address_City").attr("required", "required");
        $('#divAddressState').show();
        $("#Address_State").attr("required", "required");
        $('#divAddressCountry').show();
        $("#Address_Country").attr("required", "required");
      }
      else {
        $('#divAddressCity').hide();
        $("#Address_City").removeAttr("required");
        $('#divAddressState').hide();
        $("#Address_State").removeAttr("required");
        $('#divAddressCountry').hide();
        $("#Address_Country").removeAttr("required");
      }
    }
</script>
<script src="~/Scripts/App/App.js"></script>

Final-Merge/Pubsite-VentesB2B/Views/Events/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<Pubsite_VentesB2B.Models.Event>

@{
  ViewBag.Title = "Index";
  Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}

<h2>Search Events</h2>
@using (Html.BeginForm("Index", "Events", FormMethod.Get))
{
  <div class="form-group">
    <div class="row">
      <div class="col-md-2">
      </div>
      <div class="col-md-6">
        <div class="input-group mb-3">
          <input type="text" class="form-control" id="searchText" name="searchText" placeholder="Search" aria-label="News Title" aria-describedby="basic-addon2">
          <input type="hidden" class="form-control" id="Type" name="Type" value="@Request.QueryString["Type"]" />
          <div class="input-group-append">
            <input type="submit" id="btnSubmit" class="input-group-text" />
          </div>
        </div>
      </div>
      <div>
      </div>
    </div>
  </div>
}
<p>
  @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.First().ContentDetail.Title)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.First().ContentDetail.Description)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.First().EventType)
    </th>
    <th>
      Location
    </th>
    <th></th>
  </tr>
  @foreach (var item in Model)
  {
    <tr>
      <td>
        @Html.DisplayFor(modelItem => item.ContentDetail.Title)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.ContentDetail.Description)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.EventType)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Address.State)/@Html.DisplayFor(modelItem => item.Address.Country)
      </td>
      <td>
        @Html.ActionLink("Details", "Details", new { id = item.EventID })
      </td>
    </tr>
  }

</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, Type = Request.QueryString["Type"], searchText = Request.QueryString["searchText"] }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true })