Final-Merge/Pubsite-VentesB2B/Models/Company.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;
using System.Runtime.Serialization;
using System.Web;

namespace Pubsite_VentesB2B.Models
{
    [Table("Company")]
    public partial class Company
    {
        [Key]
        public int CompanyID { get; set; }

        [StringLength(1000)]
        public string CompanyName { get; set; }

        public string Description { get; set; }

        [StringLength(1000)]
        [DataType(DataType.Url)]
        public string WebsiteURL { get; set; }

        [StringLength(1000)]
        public string LogoImage { get; set; }

        public bool HideOnSite { get; set; }

        public DateTime? CreatedDate { get; set; }

        public DateTime? UpdatedDate { get; set; }

        public string CreatedById { get; set; }
        public string UpdatedById { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ApplicationUser CreatedBy { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ApplicationUser UpdatedBy { get; set; }

        public int? AddressID { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Address Address { get; set; }

        //Not Mapped are below
        [NotMapped]
        public HttpPostedFileBase Upload { get; set; }
    }
}

Final-Merge/Pubsite-VentesB2B/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Pubsite_VentesB2B.Models;
using PagedList;
using PagedList.Mvc;

namespace Pubsite_VentesB2B.Controllers
{
    [Authorize]
    public class CompaniesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Companies
        public ActionResult Index(int? Page, string searchText = "")
        {
            searchText = searchText.Trim();
            var companies = db.Companies.Where(c=>(c.CompanyName.Contains(searchText))).OrderByDescending(c=>c.CompanyID).ToList().ToPagedList(Page ?? 1, 10);
            return View(companies);
        }

        // GET: Companies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Company company)
        {
            if (ModelState.IsValid)
            {
                if (company.Upload != null && company.Upload.ContentLength > 0)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(company.Upload.FileName);
                    string path = Path.Combine(Server.MapPath("~/Uploads/Companies/Images"), fileName);
                    company.Upload.SaveAs(path);
                    company.LogoImage = "Uploads/Companies/Images/" + fileName;
                }
                ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
                company.CreatedDate = DateTime.Now;
                company.UpdatedDate = DateTime.Now;
                company.CreatedById = user.Id;
                company.UpdatedById = user.Id;
                db.Companies.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.AddressID = new SelectList(db.Addresses, "AddressID", "DetailAddress", company.AddressID);
            return View(company);
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            //ViewBag.AddressID = new SelectList(db.Addresses, "AddressID", "DetailAddress", company.AddressID);
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Company company)
        {
            if (ModelState.IsValid)
            {
                if (company.Upload !=null && company.Upload.ContentLength > 0)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(company.Upload.FileName);
                    string path = Path.Combine(Server.MapPath("~/Uploads/Companies/Images"), fileName);
                    company.Upload.SaveAs(path);
                    company.LogoImage = "Uploads/Companies/Images/" + fileName;
                }
                ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
                company.UpdatedDate = DateTime.Now;
                company.UpdatedById = user.Id;

                db.Entry(company).State = EntityState.Modified;
                //db.Entry(company.Address).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.AddressID = new SelectList(db.Addresses, "AddressID", "DetailAddress", company.AddressID);
            return View(company);
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthFilter(Roles ="AppAdmin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Company company = db.Companies.Find(id);
            db.Companies.Remove(company);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Final-Merge/Pubsite-VentesB2B/Views/Companies/Create.cshtml
@model Pubsite_VentesB2B.Models.Company

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Companies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Company</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, "Company Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = 5 })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WebsiteURL, "Website URL/Domain", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WebsiteURL, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.WebsiteURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Upload, "Logo Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Upload, new { type = "file" })
            </div>
        </div>

        <div class="form-group">
          <div class="col-md-10">
            @Html.CheckBoxFor(model => model.HideOnSite)
            @Html.LabelFor(model => model.HideOnSite, "Hide On Site", htmlAttributes: new { @class = "control-label col-md-2" })
          </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Final-Merge/Pubsite-VentesB2B/Views/Companies/Delete.cshtml
@model Pubsite_VentesB2B.Models.Company

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <table class="table col-md-12">
      <tr>
        <td>@Html.DisplayName("Company Name")</td>
        <td>@Html.DisplayFor(model => model.CompanyName)</td>
      </tr>
      <tr>
        <td>@Html.DisplayNameFor(model => model.Description)</td>
        <td>@Html.DisplayFor(model => model.Description)</td>
      </tr>
      <tr>
        <td>@Html.DisplayName("Website URL/Domain")</td>
        <td>@Html.DisplayFor(model => model.WebsiteURL)</td>
      </tr>
      <tr>
        <td>@Html.DisplayName("Logo Image")</td>
        <td><img src="~/@Html.DisplayFor(model=>model.LogoImage)" class="col-md-8" alt="Image" /></td>
      </tr>
      <tr>
        <td>@Html.DisplayNameFor(model => model.HideOnSite)</td>
        <td>@Html.DisplayFor(model => model.HideOnSite)</td>
      </tr>
    </table>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Final-Merge/Pubsite-VentesB2B/Views/Companies/Details.cshtml
@model Pubsite_VentesB2B.Models.Company

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Company</h4>
    <table class="table col-md-12">
      <tr>
        <td>@Html.DisplayName("Company Name")</td>
        <td>@Html.DisplayFor(model => model.CompanyName)</td>
      </tr>
      <tr>
        <td>@Html.DisplayNameFor(model => model.Description)</td>
        <td>@Html.DisplayFor(model => model.Description)</td>
      </tr>
      <tr>
        <td>@Html.DisplayName("Website URL/Domain")</td>
        <td>@Html.DisplayFor(model => model.WebsiteURL)</td>
      </tr>
      <tr>
        <td>@Html.DisplayName("Logo Image")</td>
        <td><img src="~/@Html.DisplayFor(model=>model.LogoImage)" class="col-md-8" alt="Image" /></td>
      </tr>
      <tr>
        <td>@Html.DisplayNameFor(model => model.HideOnSite)</td>
        <td>@Html.DisplayFor(model => model.HideOnSite)</td>
      </tr>
    </table>
</div>
<br /><br />
<p>

    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Edit", "Edit", new { id = Model.CompanyID }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.CompanyID})
</p>

Final-Merge/Pubsite-VentesB2B/Views/Companies/Edit.cshtml
@model Pubsite_VentesB2B.Models.Company

@{
    ViewBag.Title = "Edit Company";
    Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}

<h2>Edit Company</h2>


@using (Html.BeginForm("Edit", "Companies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
  <h4>Company</h4>
  <hr />
  @Html.ValidationSummary(true, "", new { @class = "text-danger" })
  @Html.HiddenFor(model => model.CompanyID)
  @Html.HiddenFor(model => model.LogoImage)
  <div class="form-group">
    @Html.LabelFor(model => model.CompanyName, "Company Name", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
      @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
      @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
    </div>
  </div>

  <div class="form-group">
    @Html.LabelFor(model => model.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
      @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = 5 })
      @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
    </div>
  </div>

  <div class="form-group">
    @Html.LabelFor(model => model.WebsiteURL, "Website URL/Domain", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
      @Html.EditorFor(model => model.WebsiteURL, new { htmlAttributes = new { @class = "form-control" } })
      @Html.ValidationMessageFor(model => model.WebsiteURL, "", new { @class = "text-danger" })
    </div>
  </div>

  <div class="form-group">
    @Html.LabelFor(model => model.Upload, "Logo Image", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
      @Html.TextBoxFor(model => model.Upload, new { type = "file" })
    </div>
  </div>
  <div class="form-group">
    @Html.LabelFor(model => model.LogoImage, "Current Logo Image", htmlAttributes: new { @class = "control-label col-md-3" })
    <div class="col-md-9">
      <td><img src="~/@Html.DisplayFor(model=>model.LogoImage)" alt="Image" class="col-md-8" /></td>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-10">
      @Html.CheckBoxFor(model => model.HideOnSite)
      @Html.LabelFor(model => model.HideOnSite, "Hide On Site", htmlAttributes: new { @class = "control-label col-md-2" })
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
      <input type="submit" value="Update" class="btn btn-default" />
    </div>
  </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Final-Merge/Pubsite-VentesB2B/Views/Companies/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<Pubsite_VentesB2B.Models.Company>

@{
  ViewBag.Title = "Index";
  Layout = "~/Views/Shared/_TemplateLayout.cshtml";
}
<h2>Search Companies </h2>
@using (Html.BeginForm("Index", "Companies", FormMethod.Get))
{
  <div class="form-group">
    <div class="row">
      <div class="col-md-2">
      </div>
      <div class="col-md-6">
        <div class="input-group mb-3">
          <input type="text" class="form-control" id="searchText" name="searchText" placeholder="Search" aria-label="News Title" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <input type="submit" id="btnSubmit" class="input-group-text" />
          </div>
        </div>
      </div>
      <div>
      </div>
    </div>
  </div>
}
<p>
  @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.First().CompanyName)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.First().Description)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.First().WebsiteURL)
    </th>
    <th>
      @Html.DisplayName("Logo Image")
    </th>
    <th></th>
  </tr>
  @foreach (var item in Model)
  {
    <tr>
      <td>
        @Html.DisplayFor(modelItem => item.CompanyName)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Description)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.WebsiteURL)
      </td>
      <td>
        <img src="~/@Html.DisplayFor(model=>item.LogoImage)" style="width:100px" alt="Image" />
      </td>
      <td>
        @Html.ActionLink("Details", "Details", new { id = item.CompanyID })
      </td>
    </tr>
  }
</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, searchText = Request.QueryString["searchText"] }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true })